import {
  ArrowLeft,
  CirclePause,
  Clock3,
  Lightbulb,
  Mic2,
  Sparkles,
  Square,
  Volume2,
} from "lucide-react";
import type { InterviewMode } from "../data/interviewData";

export function InterviewScreen({ mode, role, company, question, answer, isRecording, onAnswerChange, onRecordingChange, onExit, onFinish, elapsedSeconds, questionNumber, totalQuestions }: { mode: InterviewMode; role: string; company: string; question: string; answer: string; isRecording: boolean; onAnswerChange: (value: string) => void; onRecordingChange: (value: boolean) => void; onExit: () => void; onFinish: () => void; elapsedSeconds: number; questionNumber: number; totalQuestions: number; }) {
  return <section className="animate-in p-5 sm:p-8 lg:p-10"><header className="flex flex-wrap items-center justify-between gap-4"><div><button type="button" onClick={onExit} className="mb-3 inline-flex items-center gap-2 text-sm font-semibold text-violet-700 transition hover:text-violet-950"><ArrowLeft size={16} aria-hidden="true" /> Leave session</button><div className="flex items-center gap-3"><p className="font-[Lexend] text-2xl font-semibold tracking-[-0.03em] sm:text-3xl">Mock interview</p><span className="rounded-full bg-violet-100 px-3 py-1 text-sm font-semibold text-violet-800">Question {questionNumber} of {totalQuestions}</span></div><p className="mt-2 text-slate-600">{role} · {company} · {mode}</p></div><div className="flex items-center gap-3 rounded-2xl bg-violet-50 px-4 py-3 text-violet-950"><Clock3 size={20} aria-hidden="true" /><div><p className="text-xs font-semibold text-violet-700">Answer time</p><p className="font-[Lexend] text-lg font-semibold">
  {formatTime(elapsedSeconds)}
</p></div></div></header>
    <div className="mt-8 grid gap-6 xl:grid-cols-[minmax(0,1fr)_270px]"><div className="min-w-0"><section className="rounded-3xl bg-slate-950 p-6 text-white shadow-xl shadow-slate-300 sm:p-8"><div className="flex flex-wrap items-center justify-between gap-3"><span className="inline-flex items-center gap-2 rounded-full bg-violet-500/20 px-3 py-1 text-sm font-semibold text-violet-100"><Sparkles size={16} aria-hidden="true" /> Your question</span><button type="button" className="inline-flex items-center gap-2 text-sm font-semibold text-violet-100 transition hover:text-white"><Volume2 size={17} aria-hidden="true" /> Read aloud</button></div><h1 className="mt-8 max-w-3xl text-balance font-[Lexend] text-2xl font-semibold leading-tight tracking-[-0.03em] sm:text-3xl">{question}</h1><p className="mt-5 max-w-2xl text-base leading-7 text-slate-300">Answer as if your interviewer is in the room. A clear example and a thoughtful reflection are more useful than a perfect script.</p></section>
      <section className="mt-6 rounded-3xl border border-violet-100 p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-[Lexend] text-xl font-semibold tracking-[-0.02em]">Your response</p><p className="mt-1 text-sm text-slate-600">Speak naturally, or use notes to keep your story on track.</p></div><span className={`inline-flex items-center gap-2 rounded-full px-3 py-1.5 text-sm font-semibold ${isRecording ? "bg-pink-50 text-pink-700" : "bg-slate-100 text-slate-600"}`}><span className={`size-2 rounded-full ${isRecording ? "bg-pink-500 animate-pulse" : "bg-slate-400"}`} />{isRecording ? "Listening" : "Ready when you are"}</span></div><textarea value={answer} onChange={(event) => onAnswerChange(event.target.value)} className="mt-6 min-h-40 w-full resize-y rounded-2xl bg-violet-50 p-4 text-base leading-7 text-slate-900 placeholder:text-slate-500 focus:bg-white" placeholder="Jot down key points here if it helps. Your notes stay on this device for this sample session." aria-label="Answer notes" /><div className="mt-5 flex flex-wrap items-center justify-between gap-4"><button type="button" onClick={() => onRecordingChange(!isRecording)} className={`inline-flex items-center gap-2 rounded-xl px-5 py-3 font-semibold text-white transition ${isRecording ? "bg-slate-800 hover:bg-slate-700" : "bg-pink-500 hover:bg-pink-400"}`}>{isRecording ? <CirclePause size={18} aria-hidden="true" /> : <Mic2 size={18} aria-hidden="true" />}{isRecording ? "Pause practice" : "Start answering"}</button><button type="button" onClick={onFinish} className="inline-flex items-center gap-2 rounded-xl border border-violet-200 px-5 py-3 font-semibold text-violet-800 transition hover:border-violet-400 hover:bg-violet-50"><Square size={16} aria-hidden="true" /> Finish response</button></div></section></div>
      <aside className="rounded-3xl bg-violet-50 p-6 xl:self-start"><div className="flex items-center gap-2 text-violet-800"><Lightbulb size={19} aria-hidden="true" /><p className="font-[Lexend] font-semibold">A quick structure</p></div><ol className="mt-5 space-y-4 text-sm leading-6 text-violet-950"><li><span className="font-semibold">Situation</span><br />Set the context in one or two sentences.</li><li><span className="font-semibold">Task</span><br />Explain what you were responsible for.</li><li><span className="font-semibold">Action</span><br />Focus on the choices you made.</li><li><span className="font-semibold">Result</span><br />Share what changed and what you learned.</li></ol><p className="mt-6 border-t border-violet-200 pt-4 text-sm leading-6 text-violet-900">You can pause at any time. There is no live scoring while you speak.</p></aside></div></section>;
}

function formatTime(totalSeconds: number) {
  const minutes = Math.floor(totalSeconds / 60);
  const seconds = totalSeconds % 60;

  return `${String(minutes).padStart(2, "0")}:${String(seconds).padStart(2, "0")}`;
}